version: '3.0'
services:
  custom_1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      SECRET: epsipoint
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - epsiprjpoin:/app/config
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # Podman socket
      #- /run/podman/podman.sock:/var/run/docker.sock

    networks:
      - epsi_net

volumes:
  epsiprjpoin: