version: '3.0'
services:
  epsilab:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8001
      SECRET: epsipoint
    restart: unless-stopped
    ports:
      - 8001:8001
    volumes:
      - Docker_WebUI:/app/config
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # Podman socket
      #- /run/podman/podman.sock:/var/run/docker.sock
    networks:
      - epsi_net

volumes:
  Docker_WebUI:

networks:
  epsi_net:
    driver: bridge