version: '3.0'
services:
  epsilab:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      SECRET: epsipoint
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - Docker_WebUI:/app/config
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # Podman socket
      #- /run/podman/podman.sock:/var/run/docker.sock
    networks:
      - epsi_net

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - Docker_WebUI:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  Docker_WebUI:

networks:
  epsi_net:
    driver: bridge